### ISSUE TITLE
Failing PyTorch UT: `AttributeError("'constexpr' object has no attribute 'to'")`

### ISSUE THREAD

**Issue by jataylo** [ROCm/triton#412]
Fails at current TOT triton-mlir e1513b34e1ee4be43ec344bc74d8b33e0ccb3e60

Passes in our last pinned triton commit from Nov 3 e8a35b3968780e48df1374482d56cc6cdbb9e351

**Reproducer:**
```
import torch
from torch import device, empty, empty_strided

import triton
import triton.language as tl
from torch._dynamo.testing import rand_strided

@triton.jit
def randint64(seed, offset, low, high):
    r0, r1, r2, r3 = tl.randint4x(seed, offset)
    r0 = r0.to(tl.uint64)
    r1 = r1.to(tl.uint64)
    result = r0 | (r1 << 32)
    size = high - low
    
    # !!! This line causes the error !!!
    result = result % size.to(tl.uint64)
    
    #result = result.to(tl.int64) + low
    #return result
    return 0

@triton.jit
def triton_fn(in_ptr0, in_ptr1, out_ptr0, load_seed_offset, load_seed_offset1, xnumel, XBLOCK : tl.constexpr):
    xnumel = 1
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    tmp12 = tl.load(in_ptr1 + (0))
    tmp13 = tl.broadcast_to(tmp12, [XBLOCK])
    tmp0 = tl.load(in_ptr0 + load_seed_offset)
    tmp1 = tl.full([1], 0, tl.int32)
    tmp2 = randint64(tmp0, (tmp1).to(tl.uint32), -2147483648, 2147483648)


arg0_1 = rand_strided((1, ), (1, ), device='cuda:0', dtype=torch.int32)
buf0 = empty((2, ), device='cuda', dtype=torch.int64)
buf1 = empty((), device='cuda', dtype=torch.int32)

triton_fn[(1,)](buf0, arg0_1, buf1, 0, 1, 1, 1)
```

Produces:
```
Traceback (most recent call last):
  File "/root/triton/python/triton/compiler/code_generator.py", line 1152, in ast_to_ttir
    generator.visit(fn.parse())
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 293, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 365, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "/root/triton/python/triton/compiler/code_generator.py", line 288, in visit_compound_statement
    ret_type = self.visit(stmt)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 417, in visit_Assign
    values = self.visit(node.value)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 958, in visit_Call
    return self.call_JitFunction(fn, args, kws)
  File "/root/triton/python/triton/compiler/code_generator.py", line 926, in call_JitFunction
    generator.visit(fn.parse())
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 293, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 365, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "/root/triton/python/triton/compiler/code_generator.py", line 288, in visit_compound_statement
    ret_type = self.visit(stmt)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 417, in visit_Assign
    values = self.visit(node.value)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 469, in visit_BinOp
    rhs = self.visit(node.right)
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 945, in visit_Call
    fn = _unwrap_if_constexpr(self.visit(node.func))
  File "/root/triton/python/triton/compiler/code_generator.py", line 1035, in visit
    ret = super().visit(node)
  File "/opt/conda/envs/py_3.8/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/root/triton/python/triton/compiler/code_generator.py", line 998, in visit_Attribute
    return getattr(lhs, node.attr)
AttributeError: 'constexpr' object has no attribute 'to'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro.py", line 41, in <module>
    triton_fn[(1,)](buf0, arg0_1, buf1, 0, 1, 1, 1)
  File "<string>", line 4, in triton_fn
  File "/root/triton/python/triton/runtime/jit.py", line 434, in launcher_body
    bin = compile(self, signature=signature, device=device, constants=constants, num_warps=num_warps, num_ctas=num_ctas, num_stages=num_stages, waves_per_eu=waves_per_eu, matrix_instr_nonkdim=matrix_instr_nonkdim, enable_warp_specialization=enable_warp_specialization, enable_fp_fusion=enable_fp_fusion, extern_libs=extern_libs, configs=configs, debug=self.debug, device_type=device_type)
  File "/root/triton/python/triton/compiler/compiler.py", line 578, in compile
    next_module = compile_kernel(module)
  File "/root/triton/python/triton/compiler/compiler.py", line 447, in <lambda>
    lambda src: optimize_ttir(ast_to_ttir(src, signature, configs[0], constants, debug=debug, target=target), target))
  File "/root/triton/python/triton/compiler/code_generator.py", line 1161, in ast_to_ttir
    raise CompilationError(fn.src, node, repr(e)) from e
triton.compiler.errors.CompilationError: at 10:62:def triton_fn(in_ptr0, in_ptr1, out_ptr0, load_seed_offset, load_seed_offset1, xnumel, XBLOCK : tl.constexpr):
    xnumel = 1
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    tmp12 = tl.load(in_ptr1 + (0))
    tmp13 = tl.broadcast_to(tmp12, [XBLOCK])
    tmp0 = tl.load(in_ptr0 + load_seed_offset)
    tmp1 = tl.full([1], 0, tl.int32)
    tmp2 = randint64(tmp0, (tmp1).to(tl.uint32), -2147483648, 2147483648)
                                                              ^
AttributeError("'constexpr' object has no attribute 'to'")
```

**Comment by jataylo** [comment]
Potentially an even simpler way to show up this error
```
import torch
from torch import device, empty
import triton
import triton.language as tl
 
@triton.jit
def triton_fn():
    a = (2147483648 - -2147483648)
    b = a.to(tl.uint64)

triton_fn[(1,)]()
```

**Comment by jataylo** [comment]
@zhanglx13 This seems to work fine on openai/triton at the present TOT at least. The upstream issue is probably a different cause.

**Comment by jataylo** [comment]
Hey @zhanglx13 @jayfurmanek, note that this one still is an issue after the latest IFU and causes ~16 UT failures on torch side.

**Comment by xiaohuguo2023** [comment]
AttributeError("'constexpr' object has no attribute 'to'"), is due to the way we're trying to convert the value of a to a tl.uint64 type in Triton. 
```
@triton.jit
def triton_fn():
    a = (2147483648 - -2147483648)
    b = a.to(tl.uint64)
```
a, b will be treated as constexpr object

and we don't have type casting method defined in class constexpr 

There are two way, define a, b as tl.tensor, it should work, or I have added a **to** method in class constexpr


https://github.com/ROCmSoftwarePlatform/triton/blob/a48ea8de3841dfd0a84d0f748f9a0dcee2e85fbf/python/triton/language/core.py#L550C1-L560C3

**Comment by xiaohuguo2023** [comment]
For the first reproducer, we still have below issue
```
ValueError('Cannot use /, #, or % with triton.language.uint64 and triton.language.int64 because they have different signedness;this is unlikely to result in a useful answer. Cast them to the same signedness.')
```
This is due to the line
```
result = result % size.to(tl.uint64)
```
Jack is checking the latest tests related to the original test

**Comment by zhanglx13** [comment]
maybe related: https://github.com/openai/triton/issues/2939

**Comment by xiaohuguo2023** [comment]
had another look, the type casting/promotion is strictly limited to tensor.

to enable type casting/promotion for constexpr, we need have **class builder** which can handle constexpr

https://github.com/ROCmSoftwarePlatform/triton/blob/1223f6077ac359e48693ca2dbe0159dcf437c288/python/triton/runtime/interpreter.py#L89

**Comment by xiaohuguo2023** [comment]
@jataylo has just confirmed that NV tests do not have constexpr issue.

**Comment by xiaohuguo2023** [comment]
quick hack turn constant to scalar tensor have let the test pass

https://github.com/xiaohuguo2023/pytorch/tree/ptUT-fix-%23412

```
 python ./test_torchinductor.py -k "test_randint_cuda"
```

**Comment by jataylo** [comment]
Still failing on pinned commit, reproducers pass with upstream backend that we are looking to migrate to,  but constexpr conversions are being removed in LLVM project, which may lead to similar workarounds such as @xiaohuguo2023's work on above to convert to tl.tensor

Reference
https://github.com/llvm/llvm-project/commit/17764d2c87bad3b9654b7310c9936c0d15e9bf96

**Comment by jataylo** [comment]
@xiaohuguo2023 note that this one is PASSING with upstream backend at commit https://github.com/openai/triton/commit/a9bc1a36470eefafe0e2ab2503b8698f1e89e7e3.
