### ISSUE TITLE
[Upstream Backend] [PyTorch UT] `RuntimeError: Triton Error [HIP]:  Code: 1, Messsage: invalid argument`

### ISSUE THREAD

**Issue by jataylo** [ROCm/triton#552]
### Problem Description

**Environment:**
Docker image: 
`rocm/pytorch-private:rocm_inductor_triton_upstream_migration_v1`
Triton branch: 
`https://github.com/jataylo/triton/tree/jack-triton-inductor-migration`
Pytorch branch: 
`https://github.com/pytorch/pytorch/tree/rocm-inductor-hip-device`

**Reproducer:**
`TORCHINDUCTOR_COMPILE_THREADS=1 python test/inductor/test_torchinductor_dynamic_shapes.py -k "test_slice_scatter_cuda" --verbose`

**Traceback:**
```
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 432, in instantiated_test
    raise rte
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "test/inductor/test_torchinductor_dynamic_shapes.py", line 464, in test_slice_scatter
    actual = cfn(a)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 390, in _fn
    return fn(*args, **kwargs)
  File "test/inductor/test_torchinductor_dynamic_shapes.py", line 455, in fn
    def fn(i):
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 390, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 100, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 152, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 937, in __call__
    return self.current_callable(inputs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 793, in run
    return model(new_inputs)
  File "/tmp/torchinductor_root/jr/cjr537onqnwgrt4lzqemm5mxgxssf43nv6wzczajnjyp7wo3fq3i.py", line 90, in call
    triton_poi_fused_ones_0.run(buf0, s0, triton_poi_fused_ones_0_xnumel, grid=grid(triton_poi_fused_ones_0_xnumel), stream=stream0)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 675, in run
    return launcher(
  File "<string>", line 7, in launcher
  File "/root/triton/python/triton/backends/amd/driver.py", line 256, in __call__
    self.launch(*args, **kwargs)
RuntimeError: Triton Error [HIP]:  Code: 1, Messsage: invalid argument
```

### Operating System

-

### CPU

-

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.0.0

**Comment by jataylo** [comment]
Hey @micmelesse I'm not able to isolate this further. If I run the generated code after codegen we actually don't see this issue,  so it seems to only occur in initial compilation.

Is there any debug options in Triton that can get us more details on the error here?

Using pdb we can see the launch args:
```
/root/triton/python/triton/backends/amd/driver.py(256)__call__()
self.launch(*args, **kwargs)
(4, 1, 1, 4, 1, 1, 1, 1, 0, 148160048, 156739824, None, None, KernelMetadata(AMDGCN_ENABLE_DUMP=False, DISABLE_FAST_REDUCTION=False, DISABLE_LLVM_OPT=False, DISABLE_MMA_V3=False, DISABLE_PTXAS_OPT=False, LLVM_IR_ENABLE_DUMP=False, MLIR_ENABLE_DIAGNOSTICS=False, MLIR_ENABLE_DUMP=False, TRITON_DISABLE_LINE_INFO=False, TRITON_DISABLE_RESHAPE_ENCODING_INFERENCE=False, TRITON_ENABLE_LLVM_DEBUG=False, allow_fp8e4nv=False, arch='gfx90a', capability=None, cluster_dims=[1, 1, 1], debug=False, enable_fp_fusion=True, extern_libs=[['cuda2gcn', '/root/triton/python/triton/backends/amd/lib/cuda2gcn.bc'], ['opencl', '/root/triton/python/triton/backends/amd/lib/opencl.bc'], ['ocml', '/root/triton/python/triton/backends/amd/lib/ocml.bc'], ['ockl', '/root/triton/python/triton/backends/amd/lib/ockl.bc'], ['oclc_finite_only_off', '/root/triton/python/triton/backends/amd/lib/oclc_finite_only_off.bc'], ['oclc_daz_opt_off', '/root/triton/python/triton/backends/amd/lib/oclc_daz_opt_off.bc'], ['oclc_correctly_rounded_sqrt_on', '/root/triton/python/triton/backends/amd/lib/oclc_correctly_rounded_sqrt_on.bc'], ['oclc_unsafe_math_off', '/root/triton/python/triton/backends/amd/lib/oclc_unsafe_math_off.bc'], ['oclc_wavefrontsize64_on', '/root/triton/python/triton/backends/amd/lib/oclc_wavefrontsize64_on.bc'], ['oclc_abi_version_400', '/root/triton/python/triton/backends/amd/lib/oclc_abi_version_400.bc'], ['oclc_isa_version_90a', '/root/triton/python/triton/backends/amd/lib/oclc_isa_version_90a.bc']], hash='625e7e862af61a8eb717659f37739ef86808f4205e8d2477457f95395ece6253', matrix_core_version=2, matrix_inst_shape=0, max_num_imprecise_acc_default=0, name='triton__0d12d', num_ctas=1, num_stages=1, num_warps=4, shared=0, target=['hip', 'gfx90a', 64], warp_size=64, waves_per_eu=1), tensor([[2.0039, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        ...,
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],
       device='cuda:0'), 16, 1024)
```

**Comment by zhanglx13** [comment]
>  If I run the generated code after codegen we actually don't see this issue

It seems that the launcher in triton emits this runtime error. When you run the generated code, I guess you are using something different from the one triton is using. Maybe you can compare the arguments at [here](https://github.com/openai/triton/blob/e8e45a445326750852f5cea063adfd7d3b10f84e/third_party/amd/backend/driver.py#L133) and the launch function you used.

**Comment by micmelesse** [comment]
522 is the same thing as before with inductor sending args that is not insync with top of tree triton.  If I force it into the list, I get a familar error. I gor this error with this, https://github.com/micmelesse/triton/tree/micmelesse/pytorch_522 branch. It is the previous branch but it just forces target into a list. So I think this is an inductor being out of sync issue.


``` 
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 937, in __call__
    return self.current_callable(inputs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 793, in run
    return model(new_inputs)
  File "/tmp/torchinductor_root/jr/cjr537onqnwgrt4lzqemm5mxgxssf43nv6wzczajnjyp7wo3fq3i.py", line 90, in call
    triton_poi_fused_ones_0.run(buf0, s0, triton_poi_fused_ones_0_xnumel, grid=grid(triton_poi_fused_ones_0_xnumel), stream=stream0)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 675, in run
    return launcher(
  File "<string>", line 7, in launcher
  File "/root/triton_micmelesse/python/triton/backends/amd/driver.py", line 284, in __call__
    self.launch(*args, **kwargs)
TypeError: function takes exactly 12 arguments (17 given)

```

**Comment by jataylo** [comment]
> 522 is the same thing as before with inductor sending args that is not insync with top of tree triton. If I force it into the list, I get a familar error. I gor this error with this, https://github.com/micmelesse/triton/tree/micmelesse/pytorch_522 branch. It is the previous branch but it just forces target into a list. So I think this is an inductor being out of sync issue.
> 
> ```
>   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 937, in __call__
>     return self.current_callable(inputs)
>   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 793, in run
>     return model(new_inputs)
>   File "/tmp/torchinductor_root/jr/cjr537onqnwgrt4lzqemm5mxgxssf43nv6wzczajnjyp7wo3fq3i.py", line 90, in call
>     triton_poi_fused_ones_0.run(buf0, s0, triton_poi_fused_ones_0_xnumel, grid=grid(triton_poi_fused_ones_0_xnumel), stream=stream0)
>   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 675, in run
>     return launcher(
>   File "<string>", line 7, in launcher
>   File "/root/triton_micmelesse/python/triton/backends/amd/driver.py", line 284, in __call__
>     self.launch(*args, **kwargs)
> TypeError: function takes exactly 12 arguments (17 given)
> ```

This is due to running on TOT openai triton, there is currently API difference between inductor and TOT. Meta are scoping out PR to resolve.

In the meantime we should debug on https://github.com/jataylo/triton/commit/989adb9a29496c22a36ef82ca69cad5dad536b9c (or for some cherry picked ROCM fixes we can use https://github.com/jataylo/triton/commits/jack-triton-inductor-migration) as this is what is currently used by upstream pytorch today.

**Comment by zhanglx13** [comment]
@jataylo Is this fixed?

**Comment by TNT3530** [comment]
I am similarly getting this error when attempting to use Triton with [Unsloth](https://github.com/unslothai/unsloth/)
```
RuntimeError: Triton Error [HIP]:  Code: 1, Messsage: invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/model/finetune.py", line 97, in <module>
    trainer_stats = trainer.train()
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/trl/trainer/sft_trainer.py", line 361, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "<string>", line 361, in _fast_inner_training_loop
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/trainer.py", line 3161, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/accelerate/utils/operations.py", line 825, in forward
    return model_forward(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/accelerate/utils/operations.py", line 813, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/unsloth/models/llama.py", line 882, in PeftModelForCausalLM_fast_forward
    return self.base_model(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/unsloth/models/llama.py", line 847, in _CausalLM_fast_forward
    loss = fast_cross_entropy_loss(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/unsloth/kernels/cross_entropy_loss.py", line 274, in fast_cross_entropy_loss
    loss = Fast_CrossEntropyLoss.apply(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/unsloth/kernels/cross_entropy_loss.py", line 219, in forward
    _chunked_cross_entropy_forward[(n_rows, n_chunks,)](
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/triton/runtime/jit.py", line 581, in run
    bin.c_wrapper(
SystemError: <built-in function launch> returned a result with an error set```
