### ISSUE TITLE
Errors in running test / performance benchmarks

### ISSUE THREAD

**Issue by rohitnanda1443** [ROCm/triton#648]
I installed AMD-Triton using this guide: https://rocm.docs.amd.com/en/latest/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.html

Trying to run the tests: 
`python perf-kernels/flash-attention.py 
Traceback (most recent call last):
  File "/home/rohit/vllm/triton/python/perf-kernels/flash-attention.py", line 28, in <module>
    import triton
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/__init__.py", line 8, in <module>
    from .runtime import (
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/runtime/autotuner.py", line 7, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/testing.py", line 8, in <module>
    from . import language as tl
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/language/__init__.py", line 4, in <module>
    from . import math
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/language/math.py", line 5, in <module>
    from . import core
  File "/home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/language/core.py", line 8, in <module>
    from .._C.libtriton.triton import ir
ImportError: /home/rohit/miniconda3/envs/vllm/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/rohit/miniconda3/envs/vllm/lib/python3.10/site-packages/triton-2.1.0-py3.10-linux-x86_64.egg/triton/_C/libtriton.so)
`
help requested to resolve this. 

Aim: To get vllm working on a gentoo system.

**Comment by taylding-amd** [comment]
Hi @rohitnanda1443, I was not able to reproduce your error
![image](https://github.com/user-attachments/assets/3cc11c35-c804-47e0-bd35-286825bb7ef6)

From your error message, looks there is an issue with the version of the libstdc++.so.6 library on your system. Specifically, the version GLIBCXX_3.4.30 is not found, which is required by the Triton library you are trying to use. 

Can you try `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` to check whether `GLIBCXX_3.4.30` is listed? If `GLIBCXX_3.4.30` is not listed, you can try to update your `libstdc++` by `sudo apt install libstdc++6`

**Comment by taylding-amd** [comment]
Hi, this issue will be closed now due to inactivity. Please feel free to reopen it or ask follow-up questions should further assistance be required. Thanks!
